<?php
/*
 *      badge.php
 *      
 *      Create a badge
 *      
 */
function eduConnect($dbe){
   $dbeClass=file_get_contents(LIVE_DIR.'/../commentcp/classes/db.class.php');
   $dbeClass=preg_replace('/ dbc/',' dbe',$dbeClass);
   eval('?>'.$dbeClass);
   $dbe=$dbc;
}

session_name('connect');
session_start();

if (!include('incl/base.php')) die('Base classes not found');
$vars = & get_vars();

if (checkuser()){
   $user_image=getUserImage($ul);
   $liveUser=getUser($ul);
   $uid=$liveUser['member_id'];

   if (!$uid){
      die("Login has expired");
   }else{
      $dbe=null;
      eduConnect(& $dbe);
      $cdata=array();
      $ccode=strtoupper($user['login']);
      $coupon=$dbe->arrays("SELECT coupon_id,code,comment,use_count,used_count FROM membership_coupon WHERE code LIKE '$ccode%'");
      if (count($coupon)>0) {
         $cdata=$coupon[0];
         $ccode=$cdata['code'];
      }
   }
   if (isset($vars['submit_pi'])){
 
      if ($vars['submit_pi']=='Generate'){
         if (count($coupon)==0) {
            $bid=$dbe->arrays("SELECT batch_id FROM membership_coupon ORDER BY 1 DESC LIMIT 1");
            $bid=$bid[0]['batch_id']+1;
            
            $data['code']=$vars['pi_code'];
				$data['comment']=mysql_real_escape_string($vars['pi_comment']);
				$data['use_count']=$vars['pi_count'];
				$data['used_count']=0;
				$data['begin_date']=date('Y-m-d H:i:s');
				$data['expire_date']='2037-12-31 00:00:00';
				$data['discount']='100 %';
				$data['product_id']=41;
				$data['batch_id']=$bid;
            $coupon_id=$dbc->insert('membership_coupon',$data);
            if ($coupon_id>1) {
               $msg="New coupon added successfully.";
               $cnt=1;
            }else{
               $msg="New coupon could not be added.";
               $cnt=-1;
            }
         }
         echo $msg;
      }elseif ($vars['submit_pi']=='Save'){
         $msg='Not yet implemented';
         echo $msg;
      }

   }else{
   
      if (count($vars)==0) {
         if (count($cdata)==0){
            $vars['pi_count']=100;
            $vars['pi_comment']="Generated by {$user['name_f']} {$user['name_l']}";
         }else{
            $vars['pi_count']=$cdata['use_count'];;
            $vars['pi_comment']=$cdata['comment'];;
         }
      }
      include($tmpl."coupon.html");
   }
}else{
   // not logged in amember - show the login page
   $_GET['amember_redirect_url']=$_SERVER['PHP_SELF'];
   include(LIVE_DIR.'/login.php');
}

?>
