<?php
   if (!include('incl/common.php')) die('Base classes not found');
   $title="Privacy Policy - Educator-Connect";
   $page = 'pg-static';
   $public = true;
   $user=array();
   $tmpl=LIVE_DIR.'/tmpl/';
   include($tmpl.'header.html');
?>
<div class="page hover_red">
   <div id="content">
      <h1>Privacy Policy</h1>
      <p>This Privacy Policy is applicable to the use of Educator&reg; Services by you. The Privacy Policy describes the type of information Educator&reg; collects from you and how it is used by us. This Privacy policy is applicable only to the personal information collected on Educator&reg; websites and in Educator&reg; content which is available on our websites where this privacy policy is posted. It is not applicable to any other kind of information which is collected by Educator&reg; through any other ways. This Privacy Policy is not applicable to our International Partners, or any websites which are maintained by other entities to which Educator&reg; is linked. Educator&reg; cannot be held responsible for the materials and content provided on those websites or any private information those websites may collect from you.</p>
      <p>Lastly, the terms of this Privacy Policy are subject to all laws which are applicable.</p>

      <h4>Your Consent to this Privacy Policy</h4>
      <p>If you use Educator&reg; Services then you accept to the terms of this Privacy Policy as Educator&reg; may change them from time to time if needed. This Privacy Policy is a part of the Educator&reg; terms of use and is incorporated in to it. They govern the use of Educator&reg; Service.</p>

      <h4>Personal Information</h4>
      <p>While registering or purchasing Educator&reg; Service, you may be asked for your basic details like name, age, email, country, location and your residential details along with billing details(credit card number and personal information). Educator&reg; can also collect and preserve other information about the classes you have, and other information which you may voluntarily choose to provide which includes pictures and other identity information.</p>

      <h4>Right to Opt in and Opt Out</h4>
      <p>You have the power to &#147;opt-in&#148; and &#147;opt-out&#148; of certain of our uses of your private information. You can also choose or opt for not receiving any promotional emails from Educator&reg;. If you choose not to receive any promotional emails from Educator&reg;, we may still contact you in relation with your prolonged use of Educator&reg; Service.</p>

      <h4>Collection of Information via Technology</h4>
      <p>In order to improve the performance of our website, every time when you visit Educator&reg; website, the following things are automatically collected and stored by us</p>
      <ul>
         <li>The Uniform Resource Locator (URL) of the website which you linked to our website.</li>
         <li>The Internet Protocol (IP) address of the PC through which you are online.</li>
         <li>The browser which you are using.</li>
         <li>Your operating system.</li>
         <li>The date and time when you accessed our sites.</li>
         <li>URL of your target when you leave our website.</li>
      </ul>
      <p>Cookies may also be used by us which will provide you with a more personal and user friendly experience on our website. Cookies are pieces of information which are generated by our website and stored on user&#146;s computer. Cookies are used by us to maintain your website options, to automate the logins in to your website. They also help in analyzing traffic to our websites and also help in tracking downloads or referrals. This information may be related with the private information which is available in your account. &#147;Clear GIFs&#148; or pictures may be used by us which will help in analyzing the traffic on our websites. They will also be useful within HTML e-mail to check whether emails have been opened or not. Clear GIFS are also known as Web Beacons or Web Bugs. They are small images embedded in web pages and in emails. Clear Gifs are not used by us to collected or preserve any of your private information.</p>

      <h4>How Your Information is used</h4>
      <p>Whatever the purpose may be, your information will be collected only to extent necessary to fulfill you requests and our business objectives. For example, your personal information submitted through a job application is used by us to assess your candidacy or the email address which is obtained from the newsletter registration is used to deliver the newsletter emails. We utilize your personal information for the following purposes:</p>
      <ul>
         <li>Reply to your requests for extra information.</li>
         <li>Give you access to content.</li>
         <li>Let you know of the changes to the website.</li>
         <li>Provide item support, customer services and other connections related to your dealings on our website or with our products(reminders of all the posts you have made, reminders about the expiry of the posts, reminders to update them) decide if you are certified to get certain products, services or promotions, give you additional information that may be of your liking which includes marketing materials, and support other business purposes, such as development of products, applications of jobs and administration of website.</li>
      </ul>
      <h4>Sharing of Information with Third Parties</h4>
      <p>Your information will never be shared with a third party by us other than outlined in this policy. The information you provide us may be used by us to give you access to the different parts of Educator&reg; Service. The information will also be used by us for our internal record keeping purposes and we may send you notices by email and schemes and also examples of method also let you know about additional courses or any other programs in which you may be interested.</p>
      <p>Following are the methods by which third parties can have access to your information:</p>
      <p><b>1) Public Display of Information</b></p>
      <p>If you take part in community features, you will be making your username display in the public. You are also allowed to display your basic information like name, contact info through our services. Moreover our chat, tricks and forums allow you to interact with members of the online community. If you give your private info in any part of the website, that information can be collected and misused by people whom you are not familiar with and so you should never give out your private information. You should never post your full name, residential address, home phone number or any other financial information that would allow users to identify and locate you.</p>
      <p><b>2) Service Providers</b></p>
      <p>Frequently we hire other companies to carry out tasks necessary for our internal operations. For example in order to fulfill an order of games, for the delivery of promotional emails, for providing customer service, we may become affiliated with some other companies. Your personal information may be accessed by the companies hired by us, while they are providing services for us. These companies are ordered to use it mainly as requested by us for the purpose of our service. Such companies are under the obligation to preserve your personal information in confidence. Postal addresses to the U.S. Post office or other couriers may also be provided by us for delivery purposes.</p>
      <p><b>3) Aggregate Information</b></p>
      <p>We may get your Personal information and convert it into non-personally identifiable. This is done by us either by combining it with information about other individuals (mixing your information with other individuals&#146; information), and by eliminating characteristics (e.g. your date of birth). Such factors make the information personally identifiable to you. This method is called de-personalizing your information. De-personalized information may be used by us in any way and also it may be shared with third parties.</p>
      <p><b>4) Legally Compelled Disclosures</b></p>
      <p>User information may be disclosed by us whenever we are forced to do as by government authorities or whenever required or permitted by law for example like for responding to court orders and subpoenas. User information may also be disclosed by us whenever we believe that any individual could be harmed by such activities.</p>
      <h4>Purchase or Sale of Businesses/Survivability</h4>
      <p>Though currently we do not have a parent company, any subsidiaries, joint ventures under a common control, it can change in future. Your personal information may be shared with these affiliates. In that case our Affiliates should honor our Privacy Policy. If another company acquires our assets then all the personal information collected by us will be possessed by that company and all the rights and obligations concerning your personal information will be assumed by that company as described in this Privacy Policy. If our site is sold as a result of bankruptcy proceedings then also the provisions of this paragraph will apply.</p>
      <h4>Your California Privacy Rights</h4>
      <p>From 2005, under California Civil Code 1798.83 Customers who are California residents are permitted to request certain information associated with disclosure of personal information to third parties for their direct marketing interests. Our customer&#146;s personal information may be shared by us with unaffiliated third parties for their marketing interests only as described in this Privacy Policy.</p>
      <h4>If you want to know:</h4>
      <ul>
         <li>The various types of personal information that we disclosed in the previous calendar year to such third parties regarding you for the interests of the third parties&#146; marketing and/or</li>
         <li>The names and residential addresses of such third parties please use our customer support form to contact us.</li>
     </ul>
      <h4>Changes to Privacy Policy</h4>
      <p>At any time Educator&reg; may find it necessary to make changes to this Privacy Policy to make changes in the ways Educator&reg; collects or utilizes your information. Educator&reg; has the power to modify this Privacy Policy at any time by updating and re-publishing this Privacy Policy on our website. Reasonable efforts will be made by Educator&reg; to notify you of any changes, but information will be taken care of according to the Privacy Policy in effect at the time of use of the information.</p>

      <h4>Contact us</h4>
      <p>For your queries and feedback regarding our privacy practices, please contact us through our customer support form.</p>
   </div><!-- content -->
</div><!-- page -->
<?php include($tmpl.'footer.html'); ?>
