<!-- commissions -->
<div class="user-invoice-record-details-commissions">
    <em><?php __e('Commissions')?></em>
    <div class="grid-container">
        <table class="grid grid-small">
            <tr>
                <th><?php __e('Date') ?></th>
                <th><?php __e('Affiliate') ?></th>
                <th><?php __e('Product')?></th>
                <th><?php __e('Type')?></th>
                <th><?php __e('Commission')?></th>
                <th><?php __e('Paid')?></th>
                <th><?php __e('Tier')?></th>
            </tr>
            <?php foreach ($this->comm_items as $comm_item) : ?>
            <tr>
                <td><?php echo amDate($comm_item->date) ?></td>
                <td><a href="<?php p($this->userUrl($comm_item->aff_id)) ?>"><?php p($comm_item->aff_name) ?></a></td>
                <td><?php p($comm_item->product_title) ?></td>
                <td><?php p($comm_item->record_type) ?></td>
                <td><?php echo Am_Currency::render($comm_item->amount) ?></td>
                <td><?php p($comm_item->is_paid) ?></td>
                <td><?php p($comm_item->tier) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
