<div class="am-cart-product<?php echo (empty($displayProductDetails) && $di->config->get('cart.layout') == 1) ? ' am-cart-product-two-column' : '' ?>">
    <div class="am-cart-product-content">
        <div class="am-cart-product-content-title">
           <a href="<?php p($product->path ? REL_ROOT_URL . '/product/' . urlencode($product->path) : $this->pUrl(null, 'product', null, 'id', $product->pk(), 'c', $this->cc)) ?>"><?php p($product->title) ?></a>
           <div class="am-cart-product-content-terms">
           <?php
           $plans = $product->getBillingPlans(true);
           if (count($plans)==1) {
               echo $product->getBillingPlan()->getTerms();
           } else {
               $options = array();
               foreach ($plans as $plan)
                    $options[$plan->pk()] = $plan->getTerms();
               echo "<select class='billing-plan-select' name='plan[{$product->product_id}]' size='1'>\n"
               . Am_Controller::renderOptions($options, $product->default_billing_plan_id)
               . "</select>\n";
           }
           ?>
           </div>
        </div>
        <div class="am-cart-product-content-desc">
            <?php if($product->img): ?>
                <img  class="am-cart-product-content-desc-img"
                      src="<?php echo REL_ROOT_URL ?>/data/public/<?php
                        echo (!empty($displayProductDetails) && $product->img_detail_path) ?
                            $product->img_detail_path :
                            $product->img_path ?>" alt="<?php p($product->title) ?>" title="<?php p($product->title) ?>" />
            <?php endif ?>
            <?php if(empty($displayProductDetails)) : ?>
                <div class="am-cart-product-content-desc-short">
                <?php echo $product->getDescription(false); ?>
                </div>
            <?php else: ?>
                <div class="am-cart-product-content-desc-full">
                <?php echo $product->cart_description ? $product->cart_description : $product->getDescription(false) ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="am-cart-product-content-buttons">
            <input type="button" name="add" value="<?php __e('Add to Basket')?>" onclick="cart.add(this,<?php echo $product->product_id; ?>, 1)">
            <input type="button" name="order" value="<?php __e('Quick Order')?>" onclick="cart.addAndCheckout(this,<?php echo $product->product_id; ?>); ">
        </div>
    </div>
</div>