<div class="am-block">
    <div>
        <form action="<?php p(REL_ROOT_URL) ?>/helpdesk/faq/search" method="get">
            <input class="am-helpdesk-faq-q" id="am-helpdesk-faq-q" type="text" name="q" value="" placeholder="<?php __e('Type a keyword to search in FAQ') ?>" />
        </form>
    </div>
    <div id="am-helpdesk-faq-q-result" class="am-helpdesk-faq-q-result">
    </div>
</div>
<script type="text/javascript">
$('#am-helpdesk-faq-q').live('keyup', function(){
   if ($(this).val().length <= 3) {
       $("#am-helpdesk-faq-q-result").empty();
       return;
   }
   $.get($(this).closest('form').attr('action'), {q:$(this).val()}, function(html){
       $("#am-helpdesk-faq-q-result").empty().append(html);
   })
   return false;
})
</script>